return {
  {
    "mason-org/mason.nvim",
    version = "^2.0.0",
    opts = {
      ui = {
        border = "rounded",
        icons = {
          package_installed = "✓",
          package_pending = "➜",
          package_uninstalled = "✗",
        },
      },
      max_concurrent_installers = 12,
      ensure_installed = {
        "ansible-language-server",
        "ansible-lint",
        "bash-language-server",
        "eslint-lsp",
        "gci",
        "gofumpt",
        "goimports",
        "golangci-lint",
        "golangci-lint-langserver",
        "golines",
        "gomodifytags",
        "gopls",
        "gotests",
        "jq",
        "json-lsp",
        "kcl",
        "kulala-fmt",
        "lua-language-server",
        "markdownlint-cli2",
        "prettier",
        "ruff", -- Python
        "shellcheck",
        "shfmt",
        "sqlfluff",
        "stylua",
        "svelte-language-server",
        "tailwindcss-language-server",
        "taplo", -- TOML
        "terraform",
        "terraform-ls",
        "tflint",
        "typescript-language-server",
        "typos",
        "typos-lsp",
        "yaml-language-server",
        "yamlfmt",
        "yamllint",
        "yq",
      },
    },
  },
}
